pipeline {
    agent any

    triggers {
        pollSCM('* * * * *')  // Poll every minute
    }

    environment {
        IMAGE_NAME = "product-api:ci"
        CONTAINER_NAME = "product-api-test"
        PORT = "5050"
    }

    stages {

        stage('Checkout') {
            steps {
                echo 'Cloning repository from Jenkins SCM...'
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                echo 'Building Docker image...'
                sh '''
                docker build -t $IMAGE_NAME -f docker/Dockerfile .
                '''
            }
        }

        stage('Run Container Test') {
            steps {
                echo 'Starting test container...'
                sh '''
                docker rm -f $CONTAINER_NAME || true
                docker run -d -p $PORT:5000 --name $CONTAINER_NAME $IMAGE_NAME
                '''
            }
        }

        stage('Health Check') {
            steps {
                echo 'Waiting for API to boot...'
                sh 'sleep 6'

                echo 'Checking health endpoint...'
                sh '''
                curl -f http://localhost:$PORT/health
                '''
            }
        }
    }

    post {
        always {
            echo 'Cleaning up test container...'
            sh '''
            docker rm -f $CONTAINER_NAME || true
            '''
        }

        success {
            echo 'Pipeline completed successfully 🎉'
        }

        failure {
            echo 'Pipeline failed ❌'
        }
    }
}
// force rebuild - Fri Feb 13 03:03:46 PM IST 2026
