pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Start Services (API + Mongo)') {
            steps {
                sh '''
                docker compose down || true
                docker compose up -d --build
                '''
            }
        }

        stage('Wait For API') {
            steps {
                sh '''
                echo "Waiting for API to boot..."
                sleep 10
                '''
            }
        }

        stage('Health Check') {
            steps {
                sh '''
                curl -f http://localhost:5000/health
                '''
            }
        }
    }

    post {
        always {
            sh 'docker compose down'
        }
    }
}
